# Haciendo features a partir de un dataset con Pyspark

Los features o caracteristicas son representaciones numericas que caracterizan atributos de un conjunto de datos.

## Features categoricos:

In [1]:
text_file = sc.textFile('/Users/user/GitHub/PySpark-Notes/ml-100k/u.user')
text_file.collect()

[u'1|24|M|technician|85711',
 u'2|53|F|other|94043',
 u'3|23|M|writer|32067',
 u'4|24|M|technician|43537',
 u'5|33|F|other|15213',
 u'6|42|M|executive|98101',
 u'7|57|M|administrator|91344',
 u'8|36|M|administrator|05201',
 u'9|29|M|student|01002',
 u'10|53|M|lawyer|90703',
 u'11|39|F|other|30329',
 u'12|28|F|other|06405',
 u'13|47|M|educator|29206',
 u'14|45|M|scientist|55106',
 u'15|49|F|educator|97301',
 u'16|21|M|entertainment|10309',
 u'17|30|M|programmer|06355',
 u'18|35|F|other|37212',
 u'19|40|M|librarian|02138',
 u'20|42|F|homemaker|95660',
 u'21|26|M|writer|30068',
 u'22|25|M|writer|40206',
 u'23|30|F|artist|48197',
 u'24|21|F|artist|94533',
 u'25|39|M|engineer|55107',
 u'26|49|M|engineer|21044',
 u'27|40|F|librarian|30030',
 u'28|32|M|writer|55369',
 u'29|41|M|programmer|94043',
 u'30|7|M|student|55436',
 u'31|24|M|artist|10003',
 u'32|28|F|student|78741',
 u'33|23|M|student|27510',
 u'34|38|F|administrator|42141',
 u'35|20|F|homemaker|42459',
 u'36|19|F|student|93117',
 u'37|23|M|student|55105',
 u'38|28|F|other|54467',
 u'39|41|M|entertainment|01040',
 u'40|38|M|scientist|27514',
 u'41|33|M|engineer|80525',
 u'42|30|M|administrator|17870',
 u'43|29|F|librarian|20854',
 u'44|26|M|technician|46260',
 u'45|29|M|programmer|50233',
 u'46|27|F|marketing|46538',
 u'47|53|M|marketing|07102',
 u'48|45|M|administrator|12550',
 u'49|23|F|student|76111',
 u'50|21|M|writer|52245',
 u'51|28|M|educator|16509',
 u'52|18|F|student|55105',
 u'53|26|M|programmer|55414',
 u'54|22|M|executive|66315',
 u'55|37|M|programmer|01331',
 u'56|25|M|librarian|46260',
 u'57|16|M|none|84010',
 u'58|27|M|programmer|52246',
 u'59|49|M|educator|08403',
 u'60|50|M|healthcare|06472',
 u'61|36|M|engineer|30040',
 u'62|27|F|administrator|97214',
 u'63|31|M|marketing|75240',
 u'64|32|M|educator|43202',
 u'65|51|F|educator|48118',
 u'66|23|M|student|80521',
 u'67|17|M|student|60402',
 u'68|19|M|student|22904',
 u'69|24|M|engineer|55337',
 u'70|27|M|engineer|60067',
 u'71|39|M|scientist|98034',
 u'72|48|F|administrator|73034',
 u'73|24|M|student|41850',
 u'74|39|M|scientist|T8H1N',
 u'75|24|M|entertainment|08816',
 u'76|20|M|student|02215',
 u'77|30|M|technician|29379',
 u'78|26|M|administrator|61801',
 u'79|39|F|administrator|03755',
 u'80|34|F|administrator|52241',
 u'81|21|M|student|21218',
 u'82|50|M|programmer|22902',
 u'83|40|M|other|44133',
 u'84|32|M|executive|55369',
 u'85|51|M|educator|20003',
 u'86|26|M|administrator|46005',
 u'87|47|M|administrator|89503',
 u'88|49|F|librarian|11701',
 u'89|43|F|administrator|68106',
 u'90|60|M|educator|78155',
 u'91|55|M|marketing|01913',
 u'92|32|M|entertainment|80525',
 u'93|48|M|executive|23112',
 u'94|26|M|student|71457',
 u'95|31|M|administrator|10707',
 u'96|25|F|artist|75206',
 u'97|43|M|artist|98006',
 u'98|49|F|executive|90291',
 u'99|20|M|student|63129',
 u'100|36|M|executive|90254',
 u'101|15|M|student|05146',
 u'102|38|M|programmer|30220',
 u'103|26|M|student|55108',
 u'104|27|M|student|55108',
 u'105|24|M|engineer|94043',
 u'106|61|M|retired|55125',
 u'107|39|M|scientist|60466',
 u'108|44|M|educator|63130',
 u'109|29|M|other|55423',
 u'110|19|M|student|77840',
 u'111|57|M|engineer|90630',
 u'112|30|M|salesman|60613',
 u'113|47|M|executive|95032',
 u'114|27|M|programmer|75013',
 u'115|31|M|engineer|17110',
 u'116|40|M|healthcare|97232',
 u'117|20|M|student|16125',
 u'118|21|M|administrator|90210',
 u'119|32|M|programmer|67401',
 u'120|47|F|other|06260',
 u'121|54|M|librarian|99603',
 u'122|32|F|writer|22206',
 u'123|48|F|artist|20008',
 u'124|34|M|student|60615',
 u'125|30|M|lawyer|22202',
 u'126|28|F|lawyer|20015',
 u'127|33|M|none|73439',
 u'128|24|F|marketing|20009',
 u'129|36|F|marketing|07039',
 u'130|20|M|none|60115',
 u'131|59|F|administrator|15237',
 u'132|24|M|other|94612',
 u'133|53|M|engineer|78602',
 u'134|31|M|programmer|80236',
 u'135|23|M|student|38401',
 u'136|51|M|other|97365',
 u'137|50|M|educator|84408',
 u'138|46|M|doctor|53211',
 u'139|20|M|student|08904',
 u'140|30|F|student|32250',
 u'141|49|M|programmer|36117',
 u'142|13|M|other|48118',
 u'143|42|M|technician|08832',
 u'144|53|M|programmer|20910',
 u'145|31|M|entertainment|V3N4P',
 u'146|45|M|artist|83814',
 u'147|40|F|librarian|02143',
 u'148|33|M|engineer|97006',
 u'149|35|F|marketing|17325',
 u'150|20|F|artist|02139',
 u'151|38|F|administrator|48103',
 u'152|33|F|educator|68767',
 u'153|25|M|student|60641',
 u'154|25|M|student|53703',
 u'155|32|F|other|11217',
 u'156|25|M|educator|08360',
 u'157|57|M|engineer|70808',
 u'158|50|M|educator|27606',
 u'159|23|F|student|55346',
 u'160|27|M|programmer|66215',
 u'161|50|M|lawyer|55104',
 u'162|25|M|artist|15610',
 u'163|49|M|administrator|97212',
 u'164|47|M|healthcare|80123',
 u'165|20|F|other|53715',
 u'166|47|M|educator|55113',
 u'167|37|M|other|L9G2B',
 u'168|48|M|other|80127',
 u'169|52|F|other|53705',
 u'170|53|F|healthcare|30067',
 u'171|48|F|educator|78750',
 u'172|55|M|marketing|22207',
 u'173|56|M|other|22306',
 u'174|30|F|administrator|52302',
 u'175|26|F|scientist|21911',
 u'176|28|M|scientist|07030',
 u'177|20|M|programmer|19104',
 u'178|26|M|other|49512',
 u'179|15|M|entertainment|20755',
 u'180|22|F|administrator|60202',
 u'181|26|M|executive|21218',
 u'182|36|M|programmer|33884',
 u'183|33|M|scientist|27708',
 u'184|37|M|librarian|76013',
 u'185|53|F|librarian|97403',
 u'186|39|F|executive|00000',
 u'187|26|M|educator|16801',
 u'188|42|M|student|29440',
 u'189|32|M|artist|95014',
 u'190|30|M|administrator|95938',
 u'191|33|M|administrator|95161',
 u'192|42|M|educator|90840',
 u'193|29|M|student|49931',
 u'194|38|M|administrator|02154',
 u'195|42|M|scientist|93555',
 u'196|49|M|writer|55105',
 u'197|55|M|technician|75094',
 u'198|21|F|student|55414',
 u'199|30|M|writer|17604',
 u'200|40|M|programmer|93402',
 u'201|27|M|writer|E2A4H',
 u'202|41|F|educator|60201',
 u'203|25|F|student|32301',
 u'204|52|F|librarian|10960',
 u'205|47|M|lawyer|06371',
 u'206|14|F|student|53115',
 u'207|39|M|marketing|92037',
 u'208|43|M|engineer|01720',
 u'209|33|F|educator|85710',
 u'210|39|M|engineer|03060',
 u'211|66|M|salesman|32605',
 u'212|49|F|educator|61401',
 u'213|33|M|executive|55345',
 u'214|26|F|librarian|11231',
 u'215|35|M|programmer|63033',
 u'216|22|M|engineer|02215',
 u'217|22|M|other|11727',
 u'218|37|M|administrator|06513',
 u'219|32|M|programmer|43212',
 u'220|30|M|librarian|78205',
 u'221|19|M|student|20685',
 u'222|29|M|programmer|27502',
 u'223|19|F|student|47906',
 u'224|31|F|educator|43512',
 u'225|51|F|administrator|58202',
 u'226|28|M|student|92103',
 u'227|46|M|executive|60659',
 u'228|21|F|student|22003',
 u'229|29|F|librarian|22903',
 u'230|28|F|student|14476',
 u'231|48|M|librarian|01080',
 u'232|45|M|scientist|99709',
 u'233|38|M|engineer|98682',
 u'234|60|M|retired|94702',
 u'235|37|M|educator|22973',
 u'236|44|F|writer|53214',
 u'237|49|M|administrator|63146',
 u'238|42|F|administrator|44124',
 u'239|39|M|artist|95628',
 u'240|23|F|educator|20784',
 u'241|26|F|student|20001',
 u'242|33|M|educator|31404',
 u'243|33|M|educator|60201',
 u'244|28|M|technician|80525',
 u'245|22|M|student|55109',
 u'246|19|M|student|28734',
 u'247|28|M|engineer|20770',
 u'248|25|M|student|37235',
 u'249|25|M|student|84103',
 u'250|29|M|executive|95110',
 u'251|28|M|doctor|85032',
 u'252|42|M|engineer|07733',
 u'253|26|F|librarian|22903',
 u'254|44|M|educator|42647',
 u'255|23|M|entertainment|07029',
 u'256|35|F|none|39042',
 u'257|17|M|student|77005',
 u'258|19|F|student|77801',
 u'259|21|M|student|48823',
 u'260|40|F|artist|89801',
 u'261|28|M|administrator|85202',
 u'262|19|F|student|78264',
 u'263|41|M|programmer|55346',
 u'264|36|F|writer|90064',
 u'265|26|M|executive|84601',
 u'266|62|F|administrator|78756',
 u'267|23|M|engineer|83716',
 u'268|24|M|engineer|19422',
 u'269|31|F|librarian|43201',
 u'270|18|F|student|63119',
 u'271|51|M|engineer|22932',
 u'272|33|M|scientist|53706',
 u'273|50|F|other|10016',
 u'274|20|F|student|55414',
 u'275|38|M|engineer|92064',
 u'276|21|M|student|95064',
 u'277|35|F|administrator|55406',
 u'278|37|F|librarian|30033',
 u'279|33|M|programmer|85251',
 u'280|30|F|librarian|22903',
 u'281|15|F|student|06059',
 u'282|22|M|administrator|20057',
 u'283|28|M|programmer|55305',
 u'284|40|M|executive|92629',
 u'285|25|M|programmer|53713',
 u'286|27|M|student|15217',
 u'287|21|M|salesman|31211',
 u'288|34|M|marketing|23226',
 u'289|11|M|none|94619',
 u'290|40|M|engineer|93550',
 u'291|19|M|student|44106',
 u'292|35|F|programmer|94703',
 u'293|24|M|writer|60804',
 u'294|34|M|technician|92110',
 u'295|31|M|educator|50325',
 u'296|43|F|administrator|16803',
 u'297|29|F|educator|98103',
 u'298|44|M|executive|01581',
 u'299|29|M|doctor|63108',
 u'300|26|F|programmer|55106',
 u'301|24|M|student|55439',
 u'302|42|M|educator|77904',
 u'303|19|M|student|14853',
 u'304|22|F|student|71701',
 u'305|23|M|programmer|94086',
 u'306|45|M|other|73132',
 u'307|25|M|student|55454',
 u'308|60|M|retired|95076',
 u'309|40|M|scientist|70802',
 u'310|37|M|educator|91711',
 u'311|32|M|technician|73071',
 u'312|48|M|other|02110',
 u'313|41|M|marketing|60035',
 u'314|20|F|student|08043',
 u'315|31|M|educator|18301',
 u'316|43|F|other|77009',
 u'317|22|M|administrator|13210',
 u'318|65|M|retired|06518',
 u'319|38|M|programmer|22030',
 u'320|19|M|student|24060',
 u'321|49|F|educator|55413',
 u'322|20|M|student|50613',
 u'323|21|M|student|19149',
 u'324|21|F|student|02176',
 u'325|48|M|technician|02139',
 u'326|41|M|administrator|15235',
 u'327|22|M|student|11101',
 u'328|51|M|administrator|06779',
 u'329|48|M|educator|01720',
 u'330|35|F|educator|33884',
 u'331|33|M|entertainment|91344',
 u'332|20|M|student|40504',
 u'333|47|M|other|V0R2M',
 u'334|32|M|librarian|30002',
 u'335|45|M|executive|33775',
 u'336|23|M|salesman|42101',
 u'337|37|M|scientist|10522',
 u'338|39|F|librarian|59717',
 u'339|35|M|lawyer|37901',
 u'340|46|M|engineer|80123',
 u'341|17|F|student|44405',
 u'342|25|F|other|98006',
 u'343|43|M|engineer|30093',
 u'344|30|F|librarian|94117',
 u'345|28|F|librarian|94143',
 u'346|34|M|other|76059',
 u'347|18|M|student|90210',
 u'348|24|F|student|45660',
 u'349|68|M|retired|61455',
 u'350|32|M|student|97301',
 u'351|61|M|educator|49938',
 u'352|37|F|programmer|55105',
 u'353|25|M|scientist|28480',
 u'354|29|F|librarian|48197',
 u'355|25|M|student|60135',
 u'356|32|F|homemaker|92688',
 u'357|26|M|executive|98133',
 u'358|40|M|educator|10022',
 u'359|22|M|student|61801',
 u'360|51|M|other|98027',
 u'361|22|M|student|44074',
 u'362|35|F|homemaker|85233',
 u'363|20|M|student|87501',
 u'364|63|M|engineer|01810',
 u'365|29|M|lawyer|20009',
 u'366|20|F|student|50670',
 u'367|17|M|student|37411',
 u'368|18|M|student|92113',
 u'369|24|M|student|91335',
 u'370|52|M|writer|08534',
 u'371|36|M|engineer|99206',
 u'372|25|F|student|66046',
 u'373|24|F|other|55116',
 u'374|36|M|executive|78746',
 u'375|17|M|entertainment|37777',
 u'376|28|F|other|10010',
 u'377|22|M|student|18015',
 u'378|35|M|student|02859',
 u'379|44|M|programmer|98117',
 u'380|32|M|engineer|55117',
 u'381|33|M|artist|94608',
 u'382|45|M|engineer|01824',
 u'383|42|M|administrator|75204',
 u'384|52|M|programmer|45218',
 u'385|36|M|writer|10003',
 u'386|36|M|salesman|43221',
 u'387|33|M|entertainment|37412',
 u'388|31|M|other|36106',
 u'389|44|F|writer|83702',
 u'390|42|F|writer|85016',
 u'391|23|M|student|84604',
 u'392|52|M|writer|59801',
 u'393|19|M|student|83686',
 u'394|25|M|administrator|96819',
 u'395|43|M|other|44092',
 u'396|57|M|engineer|94551',
 u'397|17|M|student|27514',
 u'398|40|M|other|60008',
 u'399|25|M|other|92374',
 u'400|33|F|administrator|78213',
 u'401|46|F|healthcare|84107',
 u'402|30|M|engineer|95129',
 u'403|37|M|other|06811',
 u'404|29|F|programmer|55108',
 u'405|22|F|healthcare|10019',
 u'406|52|M|educator|93109',
 u'407|29|M|engineer|03261',
 u'408|23|M|student|61755',
 u'409|48|M|administrator|98225',
 u'410|30|F|artist|94025',
 u'411|34|M|educator|44691',
 u'412|25|M|educator|15222',
 u'413|55|M|educator|78212',
 u'414|24|M|programmer|38115',
 u'415|39|M|educator|85711',
 u'416|20|F|student|92626',
 u'417|27|F|other|48103',
 u'418|55|F|none|21206',
 u'419|37|M|lawyer|43215',
 u'420|53|M|educator|02140',
 u'421|38|F|programmer|55105',
 u'422|26|M|entertainment|94533',
 u'423|64|M|other|91606',
 u'424|36|F|marketing|55422',
 u'425|19|M|student|58644',
 u'426|55|M|educator|01602',
 u'427|51|M|doctor|85258',
 u'428|28|M|student|55414',
 u'429|27|M|student|29205',
 u'430|38|M|scientist|98199',
 u'431|24|M|marketing|92629',
 u'432|22|M|entertainment|50311',
 u'433|27|M|artist|11211',
 u'434|16|F|student|49705',
 u'435|24|M|engineer|60007',
 u'436|30|F|administrator|17345',
 u'437|27|F|other|20009',
 u'438|51|F|administrator|43204',
 u'439|23|F|administrator|20817',
 u'440|30|M|other|48076',
 u'441|50|M|technician|55013',
 u'442|22|M|student|85282',
 u'443|35|M|salesman|33308',
 u'444|51|F|lawyer|53202',
 u'445|21|M|writer|92653',
 u'446|57|M|educator|60201',
 u'447|30|M|administrator|55113',
 u'448|23|M|entertainment|10021',
 u'449|23|M|librarian|55021',
 u'450|35|F|educator|11758',
 u'451|16|M|student|48446',
 u'452|35|M|administrator|28018',
 u'453|18|M|student|06333',
 u'454|57|M|other|97330',
 u'455|48|M|administrator|83709',
 u'456|24|M|technician|31820',
 u'457|33|F|salesman|30011',
 u'458|47|M|technician|Y1A6B',
 u'459|22|M|student|29201',
 u'460|44|F|other|60630',
 u'461|15|M|student|98102',
 u'462|19|F|student|02918',
 u'463|48|F|healthcare|75218',
 u'464|60|M|writer|94583',
 u'465|32|M|other|05001',
 u'466|22|M|student|90804',
 u'467|29|M|engineer|91201',
 u'468|28|M|engineer|02341',
 u'469|60|M|educator|78628',
 u'470|24|M|programmer|10021',
 u'471|10|M|student|77459',
 u'472|24|M|student|87544',
 u'473|29|M|student|94708',
 u'474|51|M|executive|93711',
 u'475|30|M|programmer|75230',
 u'476|28|M|student|60440',
 u'477|23|F|student|02125',
 u'478|29|M|other|10019',
 u'479|30|M|educator|55409',
 u'480|57|M|retired|98257',
 u'481|73|M|retired|37771',
 u'482|18|F|student|40256',
 u'483|29|M|scientist|43212',
 u'484|27|M|student|21208',
 u'485|44|F|educator|95821',
 u'486|39|M|educator|93101',
 u'487|22|M|engineer|92121',
 u'488|48|M|technician|21012',
 u'489|55|M|other|45218',
 u'490|29|F|artist|V5A2B',
 u'491|43|F|writer|53711',
 u'492|57|M|educator|94618',
 u'493|22|M|engineer|60090',
 u'494|38|F|administrator|49428',
 u'495|29|M|engineer|03052',
 u'496|21|F|student|55414',
 u'497|20|M|student|50112',
 u'498|26|M|writer|55408',
 u'499|42|M|programmer|75006',
 u'500|28|M|administrator|94305',
 u'501|22|M|student|10025',
 u'502|22|M|student|23092',
 u'503|50|F|writer|27514',
 u'504|40|F|writer|92115',
 u'505|27|F|other|20657',
 u'506|46|M|programmer|03869',
 u'507|18|F|writer|28450',
 u'508|27|M|marketing|19382',
 u'509|23|M|administrator|10011',
 u'510|34|M|other|98038',
 u'511|22|M|student|21250',
 u'512|29|M|other|20090',
 u'513|43|M|administrator|26241',
 u'514|27|M|programmer|20707',
 u'515|53|M|marketing|49508',
 u'516|53|F|librarian|10021',
 u'517|24|M|student|55454',
 u'518|49|F|writer|99709',
 u'519|22|M|other|55320',
 u'520|62|M|healthcare|12603',
 u'521|19|M|student|02146',
 u'522|36|M|engineer|55443',
 u'523|50|F|administrator|04102',
 u'524|56|M|educator|02159',
 u'525|27|F|administrator|19711',
 u'526|30|M|marketing|97124',
 u'527|33|M|librarian|12180',
 u'528|18|M|student|55104',
 u'529|47|F|administrator|44224',
 u'530|29|M|engineer|94040',
 u'531|30|F|salesman|97408',
 u'532|20|M|student|92705',
 u'533|43|M|librarian|02324',
 u'534|20|M|student|05464',
 u'535|45|F|educator|80302',
 u'536|38|M|engineer|30078',
 u'537|36|M|engineer|22902',
 u'538|31|M|scientist|21010',
 u'539|53|F|administrator|80303',
 u'540|28|M|engineer|91201',
 u'541|19|F|student|84302',
 u'542|21|M|student|60515',
 u'543|33|M|scientist|95123',
 u'544|44|F|other|29464',
 u'545|27|M|technician|08052',
 u'546|36|M|executive|22911',
 u'547|50|M|educator|14534',
 u'548|51|M|writer|95468',
 u'549|42|M|scientist|45680',
 u'550|16|F|student|95453',
 u'551|25|M|programmer|55414',
 u'552|45|M|other|68147',
 u'553|58|M|educator|62901',
 u'554|32|M|scientist|62901',
 u'555|29|F|educator|23227',
 u'556|35|F|educator|30606',
 u'557|30|F|writer|11217',
 u'558|56|F|writer|63132',
 u'559|69|M|executive|10022',
 u'560|32|M|student|10003',
 u'561|23|M|engineer|60005',
 u'562|54|F|administrator|20879',
 u'563|39|F|librarian|32707',
 u'564|65|M|retired|94591',
 u'565|40|M|student|55422',
 u'566|20|M|student|14627',
 u'567|24|M|entertainment|10003',
 u'568|39|M|educator|01915',
 u'569|34|M|educator|91903',
 u'570|26|M|educator|14627',
 u'571|34|M|artist|01945',
 u'572|51|M|educator|20003',
 u'573|68|M|retired|48911',
 u'574|56|M|educator|53188',
 u'575|33|M|marketing|46032',
 u'576|48|M|executive|98281',
 u'577|36|F|student|77845',
 u'578|31|M|administrator|M7A1A',
 u'579|32|M|educator|48103',
 u'580|16|M|student|17961',
 u'581|37|M|other|94131',
 u'582|17|M|student|93003',
 u'583|44|M|engineer|29631',
 u'584|25|M|student|27511',
 u'585|69|M|librarian|98501',
 u'586|20|M|student|79508',
 u'587|26|M|other|14216',
 u'588|18|F|student|93063',
 u'589|21|M|lawyer|90034',
 u'590|50|M|educator|82435',
 u'591|57|F|librarian|92093',
 u'592|18|M|student|97520',
 u'593|31|F|educator|68767',
 u'594|46|M|educator|M4J2K',
 u'595|25|M|programmer|31909',
 u'596|20|M|artist|77073',
 u'597|23|M|other|84116',
 u'598|40|F|marketing|43085',
 u'599|22|F|student|R3T5K',
 u'600|34|M|programmer|02320',
 u'601|19|F|artist|99687',
 u'602|47|F|other|34656',
 u'603|21|M|programmer|47905',
 u'604|39|M|educator|11787',
 u'605|33|M|engineer|33716',
 u'606|28|M|programmer|63044',
 u'607|49|F|healthcare|02154',
 u'608|22|M|other|10003',
 u'609|13|F|student|55106',
 u'610|22|M|student|21227',
 u'611|46|M|librarian|77008',
 u'612|36|M|educator|79070',
 u'613|37|F|marketing|29678',
 u'614|54|M|educator|80227',
 u'615|38|M|educator|27705',
 u'616|55|M|scientist|50613',
 u'617|27|F|writer|11201',
 u'618|15|F|student|44212',
 u'619|17|M|student|44134',
 u'620|18|F|writer|81648',
 u'621|17|M|student|60402',
 u'622|25|M|programmer|14850',
 u'623|50|F|educator|60187',
 u'624|19|M|student|30067',
 u'625|27|M|programmer|20723',
 u'626|23|M|scientist|19807',
 u'627|24|M|engineer|08034',
 u'628|13|M|none|94306',
 u'629|46|F|other|44224',
 u'630|26|F|healthcare|55408',
 u'631|18|F|student|38866',
 u'632|18|M|student|55454',
 u'633|35|M|programmer|55414',
 u'634|39|M|engineer|T8H1N',
 u'635|22|M|other|23237',
 u'636|47|M|educator|48043',
 u'637|30|M|other|74101',
 u'638|45|M|engineer|01940',
 u'639|42|F|librarian|12065',
 u'640|20|M|student|61801',
 u'641|24|M|student|60626',
 u'642|18|F|student|95521',
 u'643|39|M|scientist|55122',
 u'644|51|M|retired|63645',
 u'645|27|M|programmer|53211',
 u'646|17|F|student|51250',
 u'647|40|M|educator|45810',
 u'648|43|M|engineer|91351',
 u'649|20|M|student|39762',
 u'650|42|M|engineer|83814',
 u'651|65|M|retired|02903',
 u'652|35|M|other|22911',
 u'653|31|M|executive|55105',
 u'654|27|F|student|78739',
 u'655|50|F|healthcare|60657',
 u'656|48|M|educator|10314',
 u'657|26|F|none|78704',
 u'658|33|M|programmer|92626',
 u'659|31|M|educator|54248',
 u'660|26|M|student|77380',
 u'661|28|M|programmer|98121',
 u'662|55|M|librarian|19102',
 u'663|26|M|other|19341',
 u'664|30|M|engineer|94115',
 u'665|25|M|administrator|55412',
 u'666|44|M|administrator|61820',
 u'667|35|M|librarian|01970',
 u'668|29|F|writer|10016',
 u'669|37|M|other|20009',
 u'670|30|M|technician|21114',
 u'671|21|M|programmer|91919',
 u'672|54|F|administrator|90095',
 u'673|51|M|educator|22906',
 u'674|13|F|student|55337',
 u'675|34|M|other|28814',
 u'676|30|M|programmer|32712',
 u'677|20|M|other|99835',
 u'678|50|M|educator|61462',
 u'679|20|F|student|54302',
 u'680|33|M|lawyer|90405',
 u'681|44|F|marketing|97208',
 u'682|23|M|programmer|55128',
 u'683|42|M|librarian|23509',
 u'684|28|M|student|55414',
 u'685|32|F|librarian|55409',
 u'686|32|M|educator|26506',
 u'687|31|F|healthcare|27713',
 u'688|37|F|administrator|60476',
 u'689|25|M|other|45439',

In [2]:
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

#df_2 = sqlContext.read.format('com.databricks.spark.csv').options(header='false', delimiter='|').load('/Users/user/GitHub/PySpark-Notes/ml-100k/u.user')

In [3]:
import pandas as pd
df_3 = pd.read_csv('/Users/user/GitHub/PySpark-Notes/ml-100k/u.item', \
                   sep = '|',names = ['movie_id','movie_title','release_date', \
                                      'video_release_date', 'IMDb-URL','unknown','Action','Adventure',\
                                      'Animation', 'Childrens','Comedy','Crime','Documentary'\
                                      ,'Drama','Fantasy','Film-Noir','Horror','Musical','Mystery',\
                                      'Romance','Sci-Fi','Thriller', 'War' ,'Western'],encoding='iso-8859-1')
print df_3.head(2)

   movie_id       movie_title release_date  video_release_date  \
0         1  Toy Story (1995)  01-Jan-1995                 NaN
1         2  GoldenEye (1995)  01-Jan-1995                 NaN

                                            IMDb-URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1

   Adventure  Animation  Childrens   ...     Fantasy  Film-Noir  Horror  \
0          0          1          1   ...           0          0       0
1          1          0          0   ...           0          0       0

   Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western
0        0        0        0       0         0    0        0
1        0        0        0       0         1    0        0

[2 rows x 24 columns]

In [4]:
import pandas as pd
df = pd.read_csv('/Users/user/GitHub/PySpark-Notes/ml-100k/u.user', sep='|',
                 #Le podemos colocar algunos headers para mayor comodidad:
                 names = ['Age','Gender', 'Occupation', 'ZIP_CODE'])

# De la columna que nos interesa, regresamos las diferentes ocupaciones y los pasamos a una lista:
all_occupations = sorted(df['Occupation'].unique().tolist())
print 'De la columna que nos interesa, regresamos las diferentes ocupaciones y los pasamos a una lista:\n\n',all_occupations

idx = 0
all_occupations_dict = {}

for occupations in all_occupations:
    all_occupations_dict[occupations] = idx
    idx +=1
    
#Ahora generamos una representación numerica para cada tipo de ocupación:    
print "\nllave para 'administrator': %d" % all_occupations_dict['administrator']
print "llave para 'artist': %d" % all_occupations_dict['artist']
print "llave para 'doctor': %d" % all_occupations_dict['doctor']
print "llave para 'educator': %d" % all_occupations_dict['educator']
print "llave para 'engineer': %d" % all_occupations_dict['engineer']
print "llave para 'entertainment': %d" % all_occupations_dict['entertainment']
print "llave para 'executive': %d" % all_occupations_dict['executive']
print "llave para 'healthcare': %d" % all_occupations_dict['healthcare']
print "llave para 'homemaker': %d" % all_occupations_dict['homemaker']
print "llave para 'lawyer': %d" % all_occupations_dict['lawyer']
print "llave para 'librarian': %d" % all_occupations_dict['librarian']
print "llave para 'marketing': %d" % all_occupations_dict['marketing']
print "llave para 'none': %d" % all_occupations_dict['other']
print "llave para 'programmer': %d" % all_occupations_dict['programmer']
print "llave para 'retired': %d" % all_occupations_dict['retired']
print "llave para 'salesman': %d" % all_occupations_dict['salesman']
print "llave para 'scientist': %d" % all_occupations_dict['scientist']
print "llave para 'technician': %d" % all_occupations_dict['technician']
print "llave para 'writer': %d" % all_occupations_dict['writer']

De la columna que nos interesa, regresamos las diferentes ocupaciones y los pasamos a una lista:

['administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing', 'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student', 'technician', 'writer']

llave para 'administrator': 0
llave para 'artist': 1
llave para 'doctor': 2
llave para 'educator': 3
llave para 'engineer': 4
llave para 'entertainment': 5
llave para 'executive': 6
llave para 'healthcare': 7
llave para 'homemaker': 8
llave para 'lawyer': 9
llave para 'librarian': 10
llave para 'marketing': 11
llave para 'none': 13
llave para 'programmer': 14
llave para 'retired': 15
llave para 'salesman': 16
llave para 'scientist': 17
llave para 'technician': 19
llave para 'writer': 20

In [8]:
import numpy as np
#prefiero usar shape pero con len se puede
k = len(all_occupations_dict)
binary_x = np.zeros(k)


k_administrator = all_occupations_dict['administrator']
binary_x[k_administrator] = 1
print 'Binary feature vector (administrator): \n', binary_x
print '\nDimension del vector (administrator) %d'% binary_x.shape

###################################################
k_artist = all_occupations_dict['artist']
binary_x[k_artist] = 1
print 'Binary feature vector (artist): \n', binary_x
print '\nDimension del vector (artist)%d'% binary_x.shape


###################################################
k_doctor = all_occupations_dict['doctor']
binary_x[k_doctor] = 1
print 'Binary feature vector (doctor): \n', binary_x
print '\nDimension del vector (doctor)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['educator']
binary_x[k_programmer] = 1
print 'Binary feature vector (educator): \n', binary_x
print '\nDimension del vector (educator)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['engineer']
binary_x[k_programmer] = 1
print 'Binary feature vector (engineer): \n', binary_x
print '\nDimension del vector (engineer)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['entertainment']
binary_x[k_programmer] = 1
print 'Binary feature vector (entertainment): \n', binary_x
print '\nDimension del vector (entertainment)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['executive']
binary_x[k_programmer] = 1
print 'Binary feature vector (executive): \n', binary_x
print '\nDimension del vector (executive)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['healthcare']
binary_x[k_programmer] = 1
print 'Binary feature vector (healthcare): \n', binary_x
print '\nDimension del vector (healthcare)%d'% binary_x.shape

###################################################
k_programmer = all_occupations_dict['homemaker']
binary_x[k_programmer] = 1
print 'Binary feature vector (homemaker): \n', binary_x
print '\nDimension del vector (homemaker)%d'% binary_x.shape



###################################################
k_programmer = all_occupations_dict['lawyer']
binary_x[k_programmer] = 1
print 'Binary feature vector (lawyer): \n', binary_x
print '\nDimension del vector (lawyer)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['librarian']
binary_x[k_programmer] = 1
print 'Binary feature vector (librarian): \n', binary_x
print '\nDimension del vector (librarian)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['marketing']
binary_x[k_programmer] = 1
print 'Binary feature vector (marketing): \n', binary_x
print '\nDimension del vector (marketing)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['none']
binary_x[k_programmer] = 1
print 'Binary feature vector (none): \n', binary_x
print '\nDimension del vector (none)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['programmer']
binary_x[k_programmer] = 1
print 'Binary feature vector (programmer): \n', binary_x
print '\nDimension del vector (programmer)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['retired']
binary_x[k_programmer] = 1
print 'Binary feature vector (retired): \n', binary_x
print '\nDimension del vector (retired)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['salesman']
binary_x[k_programmer] = 1
print 'Binary feature vector (salesman): \n', binary_x
print '\nDimension del vector (salesman)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['scientist']
binary_x[k_programmer] = 1
print 'Binary feature vector (scientist): \n', binary_x
print '\nDimension del vector (scientist)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['technician']
binary_x[k_programmer] = 1
print 'Binary feature vector (technician): \n', binary_x
print '\nDimension del vector (technician)%d'% binary_x.shape


###################################################
k_programmer = all_occupations_dict['writer']
binary_x[k_programmer] = 1
print 'Binary feature vector (writer): \n', binary_x
print '\nDimension del vector (writer)%d'% binary_x.shape

Binary feature vector (administrator):
[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (administrator) 21
Binary feature vector (artist):
[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (artist)21
Binary feature vector (doctor):
[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (doctor)21
Binary feature vector (educator):
[ 1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (educator)21
Binary feature vector (engineer):
[ 1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (engineer)21
Binary feature vector (entertainment):
[ 1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (entertainment)21
Binary feature vector (executive):
[ 1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (executive)21
Binary feature vector (healthcare):
[ 1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (healthcare)21
Binary feature vector (homemaker):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (homemaker)21
Binary feature vector (lawyer):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (lawyer)21
Binary feature vector (librarian):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (librarian)21
Binary feature vector (marketing):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (marketing)21
Binary feature vector (none):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (none)21
Binary feature vector (programmer):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  0.  0.  0.
  0.  0.  0.]

Dimension del vector (programmer)21
Binary feature vector (retired):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.  0.
  0.  0.  0.]

Dimension del vector (retired)21
Binary feature vector (salesman):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.
  0.  0.  0.]

Dimension del vector (salesman)21
Binary feature vector (scientist):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.
  0.  0.  0.]

Dimension del vector (scientist)21
Binary feature vector (technician):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.
  0.  1.  0.]

Dimension del vector (technician)21
Binary feature vector (writer):
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.
  0.  1.  1.]

Dimension del vector (writer)21

In [ ]:
#ToDo: ahora pegamos los vectores en una sola matriz:

In [9]:
user_data_df= pd.read_csv('/Users/user/GitHub/PySpark-Notes/ml-100k/u.data'\
                       ,sep = '	', names= ['user_id', 'item_id','rating', 'time_stamp'])
user_data_df.head()

   user_id  item_id  rating  time_stamp
0      196      242       3   881250949
1      186      302       3   891717742
2       22      377       1   878887116
3      244       51       2   880606923
4      166      346       1   886397596

In [10]:
time_stamps = user_data_df['time_stamp'].tolist()
#print time_stamps

In [11]:
rating_data_raw = sc.textFile('/Users/user/GitHub/PySpark-Notes/ml-100k/u.data')
rating_data = rating_data_raw.map(lambda line: line.split("\t"))


def extract_datetime(ts):
    import datetime
    return datetime.datetime.fromtimestamp(ts)
    
timestamps = rating_data.map(lambda fields: int(fields[3]))
print 'timestamps', timestamps
hour_of_day = timestamps.map(lambda ts: extract_datetime(ts).hour)
print 'hour_of_day', hour_of_day
hour_of_day.take(5)

timestamps PythonRDD[4] at RDD at PythonRDD.scala:43
hour_of_day PythonRDD[5] at RDD at PythonRDD.scala:43

[9, 13, 1, 23, 23]

# Textual features

In [14]:
df_3['movie_title'] = df_3['movie_title'].astype('O')
print df_3['movie_title'].head()

0     Toy Story (1995)
1     GoldenEye (1995)
2    Four Rooms (1995)
3    Get Shorty (1995)
4       Copycat (1995)
Name: movie_title, dtype: object

In [15]:
# el problema es que tambien quita los numeros de los titulos de las peliculas
df_3['titles'] = df_3['movie_title'].str.extract('([a-zA-Z ]+)', expand=False).str.strip()
print df_3['titles'].head()

0     Toy Story
1     GoldenEye
2    Four Rooms
3    Get Shorty
4       Copycat
Name: titles, dtype: object

In [17]:
df_3['titles1'] = df_3['movie_title'].str.split('(', 1).str[0].str.strip()
print df_3['titles1'].head()

0     Toy Story
1     GoldenEye
2    Four Rooms
3    Get Shorty
4       Copycat
Name: titles1, dtype: object

In [18]:
df_3['titles2'] = df_3['movie_title'].str.replace(r'\([^)]*\)', '').str.strip()
print df_3['titles2'].head()

0     Toy Story
1     GoldenEye
2    Four Rooms
3    Get Shorty
4       Copycat
Name: titles2, dtype: object

In [29]:
#Con BOW de scikit
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X = count_vect.fit_transform(df_3['titles2'])
#y = df['label'].values

print X.shape

(1682, 2217)

In [42]:
new_dataframe = df_3['titles2'].to_frame()
new_dataframe.head()

      titles2
0   Toy Story
1   GoldenEye
2  Four Rooms
3  Get Shorty
4     Copycat

In [43]:
from pyspark.sql import SQLContext
spDF = sqlContext.createDataFrame(new_dataframe)
spDF.show()

+-------------------+
|            titles2|
+-------------------+
|          Toy Story|
|          GoldenEye|
|         Four Rooms|
|         Get Shorty|
|            Copycat|
|     Shanghai Triad|
|     Twelve Monkeys|
|               Babe|
|   Dead Man Walking|
|        Richard III|
|              Seven|
|Usual Suspects, The|
|   Mighty Aphrodite|
|        Postino, Il|
| Mr. Holland's Opus|
|       French Twist|
|From Dusk Till Dawn|
| White Balloon, The|
|     Antonia's Line|
| Angels and Insects|
+-------------------+
only showing top 20 rows

In [53]:
rdd = spDF.rdd
print rdd

MapPartitionsRDD[14] at javaToPython at NativeMethodAccessorImpl.java:-2

In [57]:
from pyspark.mllib.feature import Word2Vec
#inp = sc.textFile("text8_lines").map(lambda row: row.split(" "))

word2vec = Word2Vec()

#model = word2vec.fit(rdd)